### ISSUE TITLE
点击文章标题跳转页面内容为Hello World

### ISSUE THREAD

**Issue by hjunfa** [ramostear/UnaBoot#5]
文章不显示   只显示Hello World
![~K858I0Y}W1KQG 2QA44Q4R](https://user-images.githubusercontent.com/62528523/77398457-87680880-6de2-11ea-9170-472f4627bc8b.png)
![@ GKPQ1SF~CITS2U7_9)_ U](https://user-images.githubusercontent.com/62528523/77398461-89ca6280-6de2-11ea-93af-b37ee8e69cde.png)

**Comment by ramostear** [comment]
![una-logo-max-1](https://user-images.githubusercontent.com/16871115/78407208-db6eba80-7636-11ea-9c59-32e19bc4deaa.png)

你好，现已升级到1.2.2版本，补全了1.2.0版本中默认主题缺失的问题
![theme](https://user-images.githubusercontent.com/16871115/78407095-977bb580-7636-11ea-9e7c-570650069ca5.png)

你可以尝试下载最新版本的代码或者war包
![tag](https://user-images.githubusercontent.com/16871115/78407185-cc880800-7636-11ea-9820-cde7e53d8cd3.png)
