### ISSUE TITLE
 UnaBoot System has not been install,Please install and init this application

### ISSUE THREAD

**Issue by heishzc** [ramostear/UnaBoot#6]
UnaBoot System has not been install,Please install and init this application
最新版安装一直报这个，无论删除tomcat 和 项目都是一样

**Comment by heishzc** [comment]
看了下源码，在install.html 279行，你的提交地址写错了，多了unaboot，你源码路径是没有这个的，删除之后，就安装成功，所以会报上面的错误，拦截器拦截掉了

**Comment by ramostear** [comment]
谢谢！！！
升级后，后台请求地址有变动，漏掉了安装页面的表单提交地址的更改。
